### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by rupak-nm**
Fixed versions of the following:
- `@headlessui/react`         : `^1.4.2` --> `1.4.1`
- `@radix-ui/react-dialog`    : `^0.1.7` --> `0.1.0`
- `@radix-ui/react-tooltip`   : `^0.1.6` --> `0.1.0`
- `@tailwindcss/forms`        : `^0.4.0` --> `0.4.0`
- `bignumber.js`              : `^9.0.2` --> `9.0.2`
- `chart.js`                  : `3.7.0`  --> `3.5.1`
- `highcharts`                : `^9.3.3` --> `9.1.2`
- `highcharts-react-official` : `^3.1.0` --> `3.0.0`
- `uuid`                      : `^8.3.2` --> `8.3.2`

Package `react-number-format` removed and functionality rewritten in pure JS

### CODE REVIEW

**Comment by binodnpm** [comment]
A very good initiative. 👏

**Review by flashburst — APPROVED** [review]

**Review by flashburst — CHANGES_REQUESTED** [review]
Fix input format to allow decimal places

**Comment by rupak-nm** [comment]
@flashburst Done. 
Thanks for the suggestion.

**Comment by binodnpm** [comment]
@rupak-nm could you please fix the merge conflicts?

**Comment by rupak-nm** [comment]
@binodnpm done

**Pull request merged**
